# Generated by Django 5.0.6 on 2024-06-01 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AUTH_APP', '0001_initial'),
        ('offre_demande', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_applications', to='AUTH_APP.candidat')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_applications', to='offre_demande.offredemploi')),
            ],
            options={
                'unique_together': {('applicant', 'job_offer')},
            },
        ),
        migrations.CreateModel(
            name='JobApplicationRecruter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_applications', to='AUTH_APP.recruteur')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_applications', to='offre_demande.demandedemploi')),
            ],
            options={
                'unique_together': {('applicant', 'job_request')},
            },
        ),
    ]
