# Generated by Django 5.0.6 on 2024-06-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre_demande', '0002_alter_demandedemploi_date_soumission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posseder',
            name='niveau_metrise',
            field=models.CharField(choices=[('Tres Bien', 'Tres Bien'), ('Bien', 'Bien'), ('Moyenne', 'Moyenne'), ('Debutant', 'Debutant')], max_length=50),
        ),
    ]
